swagger: "2.0"
info:
  version: "1.0.0"
  title: "Product service"
host: "rlm02whct7.execute-api.eu-west-1.amazonaws.com"
basePath: "/"
schemes:
  - "https"
paths:
  /products:
    get:
      summary: "Returns list of products"
      operationId: "getProductsList"
      produces:
        - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
  /products/{productId}:
    get:
      summary: "Find product by ID"
      operationId: "getProductById"
      produces:
        - "application/json"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of product"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: "not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      description:
        type: "string"
      imgSrc:
        type: "string"
      price:
        type: "integer"
        format: "float"
      count:
        type: "integer"
        format: "int64"
  ErrorResponse:
    type: "object"
    properties:
      error:
        type: "string"
